### ISSUE TITLE
MFC feedback analog in werkt soms niet

### ISSUE THREAD

**Issue by ijager** [OperationAIR/electronics#11]
Interay meldt dat de analoge inputs voor de MFC's soms geen response geven op de testcommando's

**Comment by sjorsdewit** [comment]
lijkt gewoon te werken? Valt wel op dat ons eigen terminal programma de response niet weergeeft totdat je een ander commando uitvoert dat text-mode is (eindigend op \n)

**Comment by sjorsdewit** [comment]
boardconfig ten tijde van productietest was ook nog niet correct (ADC channels verwisseld). dit zal waarschijnlijk de oorzaan zijn geweest.
