### ISSUE TITLE
Settings validation: what should the bounds be?

### ISSUE THREAD

**Issue by sjorsdewit** [OperationAIR/electronics#15]
Each of these settings from the RPI are validated on the MCU:
- PEEP
- frequency
- peak pressure
- ratio
- oxygen

As a safety feature, the MCU ignores a set of new settings if any of them is outside a valid range (see settings.c). But what should the range of each setting be?

The current bounds may not be in agreement with the GUI, which could lead to confusion for the end-user when they are not applied..

**Comment by ijager** [comment]
Uit de feedback kwam deze tabel:

  | Default waarde | Range | Stapgrootte waarde en alarm | Alarm range default
-- | -- | -- | -- | --
PEEP [cmH2O] | 10 | 5 - 30 | 1 | 8 - 12
PC boven PEEP [cmH2O] | 15 | 5 - 40 | 2 | 20 - 30
Freqentie [/min] | 15 | 5 - 40 | 1 | -
FiO2 [%O2] | 40 | 21 - 100 | 5 | 35 - 45
I:E | 1:2 | 1:1 - 1:3 | -:0.5 | -
TV [ml] | - | - | 50 | 300 - 700
Mve [L/min] | - | - | 0.5 | 5 - 9

**Comment by sjorsdewit** [comment]
Implemented in 99f8ec7f
