### ISSUE TITLE
Drop pressure in MFC buffer after opening pressure relieve valve.

### ISSUE THREAD

**Issue by hubaldv** [OperationAIR/electronics#8]
If pressure in buffer is > 1000mbar, pressure relief valve is opened. This valve closes if pressure is <500 or <600 mbar. The software should detect that the valve is opened and let the pressure in the buffer drop below this limit such that the valve will close again.

**Comment by sjorsdewit** [comment]
Implemented in dbf1174faa512ad56f234c90fe79aa9329e03858
