### ISSUE TITLE
Flowsensor: geen error waarde

### ISSUE THREAD

**Issue by ijager** [OperationAIR/electronics#9]
Ze kunnen in friesland geen verschil zien tussen 0 flow of geen sensor aangesloten. Dus dit is een probleem voor het testen

**Comment by sjorsdewit** [comment]
flowsensor zou -1 moeten geven bij fout. Daarnaast is de[ system status](https://github.com/OperationAIR/electronics/blob/master/firmware/README.md#sensor-values-response) beschikbaar
